### ISSUE TITLE
How many epoch yu are taken for 64*64 image size

### ISSUE THREAD

**Issue by joshanjinu** [artcg/BEGAN#21] opened 2018-07-17 10:44 UTC
Im able to run the program with no error. the convergence measure is displying with no plotting. please help with further.. ! 
 image size = 64 ; 
total images  = 20000 ;
epoch=1000; 
checkpoint:975; 
no of image : 1000 (at once) ; 
other parameters are same: 
![figure_1](https://user-images.githubusercontent.com/12893485/42812690-1ae3282a-89dc-11e8-800e-664f2e22c9e6.png)
![figure_2](https://user-images.githubusercontent.com/12893485/42812691-1b1d1fee-89dc-11e8-89be-42dbdc6f72a0.png)
 plz help me.. !

**Comment by artcg** [comment] 2018-07-18 21:54
Duplicate of https://github.com/artcg/BEGAN/issues/13 which I still havent had time to look at/ see if I can recreate

I recommend using carpedm's repo for now if you are having this problem 

https://github.com/carpedm20/BEGAN-tensorflow

since I am unlikely to be able to look at this in the near future

**Closed as completed by artcg** 2018-07-18 21:54 UTC
